### ISSUE TITLE
Test Liquibase with a multi-file change log

### ISSUE THREAD

**Issue by nort3x** [spring-projects/spring-aot-smoke-tests#168]
hello,
although test in boot:liquibase passes, most of the time developers generate changelogs in separate files and include them in changelog-master,
here in [boot/liquibase/src/main/resources/db/changelog/db.changelog-master.yaml](https://github.com/spring-projects/spring-aot-smoke-tests/blob/main/boot/liquibase/src/main/resources/db/changelog/db.changelog-master.yaml)
i see a single file containing all the migrations (change-sets)

i tried countless times to make it work with multiple files like:
``` yaml
// changelog-master.yaml

databaseChangeLog:
  - include:
      relativeToChangelogFile: true
      file: change1.yaml 



// change1.yaml

databaseChangeLog:
  - changeSet:
      author: nort3x
      id: --init--

```

absolute paths, different `resource-config.json` for graalvm hints and i'm still stuck,

i think this repo should contains a more general and closer to reality structure
 
-- best regards
nort3x
